### PR TITLE
Add a way to lock ES access to specific user groups

### PR DESCRIPTION
**Pull request by mweiden**

### CODE REVIEW

**Comment by mweiden** [comment]
@kislyuk this is the best way that I could think of to lock ES permission to the list of `dcp-developer`s and `dcp-admin`s. Alternatives?

**Comment by parthshahva** [comment]
@mweiden I'm guessing make apply or this script needs to be run in the logs repo every-time one of the lists is modified in dcp-infra? It may be worth adding these instructions to the hca-id onboarding doc in dcp-infra to handle this proactively.

**Comment by mweiden** [comment]
@parthshahva I added this to the DevSecOps onboarding/offboarding docs.

**Comment by parthshahva** [comment]
Is it worth moving management of this secret to the dcp-infra repo? Metrics, tracker, other tools will probably need to read from the same lists to control access. Is it worth having all external tools just read from the list rather than modifying it based on the list already maintained in dcp infa?

**Comment by parthshahva** [comment]
> Is it worth moving management of this secret to the dcp-infra repo? Metrics, tracker, other tools will probably need to read from the same secrets to control access. Is it worth having all tools just read from the secret rather than maintaining their own list based on the list already maintained in dcp infa?

Hmm actually nevermind. Logs makes sense to restrict to developers but the other tools may need to be open to a wider audience at the partner organizations

**Comment by mweiden** [comment]
I've removed the script and pull a configuration file to retrieve this list instead. The DevSecOps onboarding documentation covers how to keep this file up-to-date.

**Pull request merged**
